# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: MSBuild@1
  displayName: 'Build solution Xamarin.Forms.GoogleMaps.Clustering.sln'
  inputs:
    solution: Xamarin.Forms.GoogleMaps.Clustering.sln
    msbuildArguments: '/t:restore;build /p:Configuration=Release'
